runners:
  - name: long-runner
    cloud: aws
    instance_type: c5d.4xlarge
    machine_image: ami-0582cf60af51d3113
    preemptible: false
    workflow: .github/workflows/conda-build.yml
    count: 2
