runners:
  - name: long-runner
    cloud: aws
    instance_type: c5d.2xlarge
    machine_image: ami-0048c368c80e3ee99
    preemptible: false
    workflow: .github/workflows/conda-build.yml
    count: 2
